language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - nose2 --with-coverage
services:
  - postgresql
addons:
  - postgresql: "10"
  - apt:
      - packages:
        - postgresql-10
        - postgresql-client-10
postgres:
  - adapter: postgresql
env:
  - global:
    - PGPORT=5433
notifications:
  - false
before_script:
  - psql -c 'create database test_hello_books;' -U postgres
after_success:
  - codecov